In [ ]:
from google.colab import drive
drive.mount('/content/drive')
!ls "/content/drive/My Drive/"

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import plotly.io as pio
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/TDS/master_currency.csv')

In [20]:
df.head()

Date       EUR       AUD       BGN       BRL       CAD       CHF  \
0  2022-05-18  1.052299  0.702494  0.538039  0.202466  0.780153  1.003512   
1  2022-05-17  1.054074  0.703037  0.538967  0.200321  0.779849  1.008065   
2  2022-05-16  1.042209  0.692185  0.532879  0.197316  0.773575  0.994530   
3  2022-05-15  1.038529  0.689275  0.530983  0.195191  0.768994  1.000000   
4  2022-05-14  1.038529  0.689275  0.530983  0.195191  0.768994  1.000000   

        CNY       CZK       DKK       GBP       HKD       HRK       ILS  \
0  0.148269  0.042695  0.141403  1.242854  0.127411  0.139655  0.298436   
1  0.148677  0.042655  0.141653  1.248907  0.127393  0.140089  0.297876   
2  0.147232  0.042177  0.140046  1.225490  0.127390  0.138544  0.293789   
3  0.147278  0.041977  0.139561  1.220107  0.127389  0.138099  0.291826   
4  0.147278  0.041977  0.139561  1.220107  0.127389  0.138099  0.291826   

        INR  
0  0.012889  
1  0.012910  
2  0.012854  
3  0.012912  
4  0.012912

In [ ]:
df.corr()

EUR       AUD       BGN       BRL       CAD       CHF       CNY  \
EUR  1.000000  0.617523  1.000000 -0.250676  0.690149  0.817383  0.143688   
AUD  0.617523  1.000000  0.617502  0.318886  0.903318  0.573215  0.202493   
BGN  1.000000  0.617502  1.000000 -0.250626  0.690167  0.817349  0.143632   
BRL -0.250676  0.318886 -0.250626  1.000000  0.119718 -0.301776 -0.183577   
CAD  0.690149  0.903318  0.690167  0.119718  1.000000  0.607070  0.175027   
CHF  0.817383  0.573215  0.817349 -0.301776  0.607070  1.000000  0.624667   
CNY  0.143688  0.202493  0.143632 -0.183577  0.175027  0.624667  1.000000   
CZK  0.869790  0.545214  0.869799 -0.121929  0.664899  0.787959  0.289659   
DKK  0.999978  0.617691  0.999978 -0.250321  0.689154  0.816951  0.142412   
GBP  0.961822  0.621241  0.961801 -0.254881  0.698446  0.893497  0.330907   
HKD  0.952371  0.492848  0.952354 -0.417496  0.620954  0.789927  0.182693   
HRK  0.998621  0.595137  0.998623 -0.264440  0.671817  0.800736  0.113588   
ILS  0.149702 -0.060304  0.149666 -0.566308  0.013075  0.503037  0.675334   
INR  0.897259  0.500419  0.897262 -0.291915  0.607822  0.767947  0.189478   

          CZK       DKK       GBP       HKD       HRK       ILS       INR  
EUR  0.869790  0.999978  0.961822  0.952371  0.998621  0.149702  0.897259  
AUD  0.545214  0.617691  0.621241  0.492848  0.595137 -0.060304  0.500419  
BGN  0.869799  0.999978  0.961801  0.952354  0.998623  0.149666  0.897262  
BRL -0.121929 -0.250321 -0.254881 -0.417496 -0.264440 -0.566308 -0.291915  
CAD  0.664899  0.689154  0.698446  0.620954  0.671817  0.013075  0.607822  
CHF  0.787959  0.816951  0.893497  0.789927  0.800736  0.503037  0.767947  
CNY  0.289659  0.142412  0.330907  0.182693  0.113588  0.675334  0.189478  
CZK  1.000000  0.868539  0.895324  0.804962  0.863414  0.236810  0.871290  
DKK  0.868539  1.000000  0.961047  0.951734  0.998713  0.150346  0.897582  
GBP  0.895324  0.961047  1.000000  0.933186  0.954695  0.263879  0.884352  
HKD  0.804962  0.951734  0.933186  1.000000  0.954524  0.230405  0.852254  
HRK  0.863414  0.998713  0.954695  0.954524  1.000000  0.146376  0.899186  
ILS  0.236810  0.150346  0.263879  0.230405  0.146376  1.000000  0.295468  
INR  0.871290  0.897582  0.884352  0.852254  0.899186  0.295468  1.000000

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
model=LinearRegression()

In [68]:
X_train=df['BGN'].values.reshape(-1,1)
y_train=df['CNY'].values

In [73]:
X_test=df['BGN'].mean().reshape(-1,1)
X_test

array([[0.58574939]])

In [69]:
model.fit(X_train,y_train)

LinearRegression()

Predicted value of currency "CNY" from currency"BGN" where the "BGN" value is the average value of the currency "BGN"

In [75]:
y_pred=model.predict(X_test)
y_pred

array([0.15572972])

In [29]:
print(model.coef_)
print(model.intercept_)

[0.01089102]
0.12031035778248675


In [76]:
X_train=df['BRL'].values.reshape(-1,1)
y_train=df['HKD'].values

In [77]:
model.fit(X_train,y_train)

LinearRegression()

Predict value of currency "CNY" from currency"BRL" where the "BRL" value is the average value of the currency "BRL"

In [79]:
X_test=df['BRL'].mean().reshape(-1,1)
X_test

array([[0.19082525]])

In [80]:
y_pred=model.predict(X_test)
y_pred

array([0.12829785])

In [49]:
def linear_regression(x, y):
    N = len(x)
    x_mean = x.mean()
    y_mean = y.mean()

    B1_num = ((x - x_mean) * (y - y_mean)).sum()
    B1_den = ((x - x_mean)**2).sum()
    B1 = B1_num / B1_den

    B0 = y_mean - (B1*x_mean)

    reg_line = 'y = {} + {}β'.format(B0, round(B1, 3))

    return (B0, B1, reg_line)

Regression slope for the currency pair- "AUD-HKD"

In [64]:
import numpy
x1 = numpy.array(df['AUD'])
y1 = numpy.array(df['HKD'])
numpy.polyfit(x1,y1,1)[0]

0.010891021828995314

Regression slope for the currency pair- "AUD-HRK"

In [65]:
import numpy
x1 = numpy.array(df['AUD'])
y1 = numpy.array(df['HRK'])
numpy.polyfit(x1,y1,1)[0]

0.19320066701178681